name: intry
description: "Intry is a highly efficient and rich UI component set designed specifically for creating editor and graphic design applications."
version: 0.0.2
homepage: 
repository: https://github.com/manjav/intry
issue_tracker: https://github.com/manjav/intry/issues
documentation: https://github.com/manjav/intry

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  math_parser:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# screenshots:
#   - description: 'LineChartSample1 and LineChartSample2'
#     path: pub_screenshots/line_chart.jpg

topics:
  - textfield
  - textinput
  - slider
  - ui
  - ux